### ISSUE TITLE
♻️ Page(Home) Modifier Slide

### ISSUE THREAD

**Issue by mbayedione10** [AfricTivistes/migrations-front#80]
Cc: @dofbi @Abdoulayeguene 

Salut @dofbi 

### Difficulté

Les posts recuperé pour le slide sont statique
Apres suppression des posts, la partie devient vides
### Tâches

- [ ] recuperer les derniers post par categorie pour affichage

### Captures d'écran

<img width="1504" alt="Screen Shot 2022-09-28 at 10 23 36" src="https://user-images.githubusercontent.com/47165947/192757351-0aab0f6f-8394-43c9-942f-58cb6d6e5c41.png">

Merci!

**Comment by mbayedione10** [comment]
Cc @dofbi 
cette partie n'est plus dispo sur le site en version FR
Merci de verifier please

**Comment by dofbi** [comment]
Salaam @mbayedione10
## Amélioration

- Avant de ce lancer à améliorer le code, il faut comprendre sa structure

## La version livrée du projet

- Propose l’utilisation d'Étiquettes pour afficher un Article à la Une (Slide)
- Il suffit d'ajouter l'étiquette Top (EN) ou Haut (FR) pour voir l'article à la Une
- Pas besoin de retirer cette étiquette ou de supprimer l'article à chaque fois qu'un article est ajouté à la Une seul les trois ressent son mis en avant.

## Attention

Je constate la suppression de l'étiquette Haut (FR) et d'autres, merci de ne pas supprimer avant ouverture d'une issue et confirmation de la suppression.

![Capture d’écran du 2022-09-28 14-45-09](https://user-images.githubusercontent.com/84446/192811027-0e202695-aadb-4b6c-879e-51366f31de58.png)

**Comment by mbayedione10** [comment]
Salam,
Merci pour ce retour
A cause de l'urgence je suis en train de faire du "learn by doing" 
Je vais y faire attention btw 👌🏿
